### PR TITLE
Fixed Celcius conversion, Re-ordered tiles

### PR DESCRIPTION
**Pull request by thrash99er**
I fixed the Celcius conversion back to where it was, and I reordered the tiles

### CODE REVIEW

**Comment by tslagle13** [comment]
No files changed here. Looks like a blank PR.

**Comment by tslagle13** [comment]
No files changed. Blank PR?

**Comment by thrash99er** [comment]
Sorry trying to figure out how Github works.

Morgan Everett
cell 509.781.0157

**Comment by tslagle13** [comment]
No problem :)

Let me know if I can help in some way. 

This is a really good article for beginners: http://readwrite.com/2013/09/30/understanding-github-a-journey-for-beginners-part-1

**Pull request closed without merging**
